-- MySQL Script generated by MySQL Workbench
-- Sat Jun 19 10:14:22 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BDProgramacion2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BDProgramacion2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BDProgramacion2` DEFAULT CHARACTER SET utf8 ;
USE `BDProgramacion2` ;

-- -----------------------------------------------------
-- Table `BDProgramacion2`.`carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDProgramacion2`.`carrera` (
  `carrera_cod` INT NOT NULL,
  `carrera_nombre` VARCHAR(45) NULL,
  `carrera_duracion` INT NULL,
  UNIQUE INDEX `carrera_cod_UNIQUE` (`carrera_cod` ASC) VISIBLE,
  PRIMARY KEY (`carrera_cod`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDProgramacion2`.`inscripcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDProgramacion2`.`inscripcion` (
  `inscripcion_cod` INT NOT NULL,
  `inscripcion_nombre` VARCHAR(45) NULL,
  `inscripcion_codCar` INT NULL,
  PRIMARY KEY (`inscripcion_cod`),
  UNIQUE INDEX `inscripcion_cod_UNIQUE` (`inscripcion_cod` ASC) VISIBLE,
  INDEX `inscripcionCarrera_idx` (`inscripcion_codCar` ASC) VISIBLE,
  CONSTRAINT `inscripcionCarrera`
    FOREIGN KEY (`inscripcion_codCar`)
    REFERENCES `BDProgramacion2`.`carrera` (`carrera_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDProgramacion2`.`alumno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDProgramacion2`.`alumno` (
  `alumno_dni` INT NOT NULL,
  `alumno_nombre` VARCHAR(45) NULL,
  `alumno_apellido` VARCHAR(45) NULL,
  `alumno_domicilio` VARCHAR(45) NULL,
  `alumno_telefono` INT NULL,
  `alumno_codInscripcion` INT NULL,
  UNIQUE INDEX `alumno_dni_UNIQUE` (`alumno_dni` ASC) VISIBLE,
  PRIMARY KEY (`alumno_dni`),
  INDEX `alumnoInscripcion_idx` (`alumno_codInscripcion` ASC) VISIBLE,
  CONSTRAINT `alumnoInscripcion`
    FOREIGN KEY (`alumno_codInscripcion`)
    REFERENCES `BDProgramacion2`.`inscripcion` (`inscripcion_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDProgramacion2`.`profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDProgramacion2`.`profesor` (
  `profesor_dni` INT NOT NULL,
  `profesor_nombre` VARCHAR(45) NULL,
  `profesor_apellido` VARCHAR(45) NULL,
  `profesor_domicilio` VARCHAR(45) NULL,
  `profesor_telefono` INT NULL,
  UNIQUE INDEX `profesor_dni_UNIQUE` (`profesor_dni` ASC) VISIBLE,
  PRIMARY KEY (`profesor_dni`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDProgramacion2`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDProgramacion2`.`materia` (
  `materia_cod` INT NOT NULL,
  `materia_nombre` VARCHAR(45) NULL,
  `materia_profDNI` INT NULL,
  PRIMARY KEY (`materia_cod`),
  UNIQUE INDEX `materia_cod_UNIQUE` (`materia_cod` ASC) VISIBLE,
  INDEX `materiaProfesor_idx` (`materia_profDNI` ASC) VISIBLE,
  CONSTRAINT `materiaProfesor`
    FOREIGN KEY (`materia_profDNI`)
    REFERENCES `BDProgramacion2`.`profesor` (`profesor_dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BDProgramacion2`.`cursado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BDProgramacion2`.`cursado` (
  `cursado_alumnoDNi` INT NOT NULL,
  `cursado_codMat` INT NOT NULL,
  `cursado_nota` INT NULL,
  PRIMARY KEY (`cursado_alumnoDNi`, `cursado_codMat`),
  UNIQUE INDEX `cursado_alumnoDNi_UNIQUE` (`cursado_alumnoDNi` ASC) VISIBLE,
  INDEX `cursadoMateria_idx` (`cursado_codMat` ASC) VISIBLE,
  CONSTRAINT `cursadoMateria`
    FOREIGN KEY (`cursado_codMat`)
    REFERENCES `BDProgramacion2`.`materia` (`materia_cod`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cursadoAlumno`
    FOREIGN KEY (`cursado_alumnoDNi`)
    REFERENCES `BDProgramacion2`.`alumno` (`alumno_dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
