-- MySQL Script generated by MySQL Workbench
-- Mon Jun 14 18:06:05 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BD_Universidad
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BD_Universidad
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BD_Universidad` DEFAULT CHARACTER SET utf8 ;
USE `BD_Universidad` ;

-- -----------------------------------------------------
-- Table `BD_Universidad`.`Alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_Universidad`.`Alumnos` (
  `dni_Alumno` INT NOT NULL AUTO_INCREMENT,
  `nombre_Alumno` VARCHAR(45) NULL,
  `apellido_Alumno` VARCHAR(45) NULL,
  `estado_Alumno` ENUM("Ingresante", "Regular", "No Regular", "Egresado") NULL,
  `email_Alumno` VARCHAR(45) NULL,
  `telefono_Alumno` INT NULL,
  PRIMARY KEY (`dni_Alumno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_Universidad`.`Profesores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_Universidad`.`Profesores` (
  `id_Profesor` INT NOT NULL AUTO_INCREMENT,
  `nombre_Profesor` VARCHAR(45) NULL,
  `apellido_Profesor` VARCHAR(45) NULL,
  `dni_Profesor` INT NULL,
  `email_Profesor` VARCHAR(45) NULL,
  `telefono_Profesor` INT NULL,
  PRIMARY KEY (`id_Profesor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_Universidad`.`Materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_Universidad`.`Materias` (
  `id_Materia` INT NOT NULL AUTO_INCREMENT,
  `nombre_Materia` VARCHAR(45) NULL,
  `descripcion_Materia` VARCHAR(45) NULL,
  `horas_Materia` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Materia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_Universidad`.`Comision`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_Universidad`.`Comision` (
  `id_Comision` VARCHAR(10) NOT NULL,
  `aula_Comision` VARCHAR(45) NULL,
  `turno_Comision` ENUM("Mañana", "Tarde", "Noche") NULL,
  PRIMARY KEY (`id_Comision`),
  UNIQUE INDEX `idComision_UNIQUE` (`id_Comision` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_Universidad`.`DictadoMateria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_Universidad`.`DictadoMateria` (
  `id_DictadoMateria` INT NOT NULL AUTO_INCREMENT,
  `ComisionFK_DictadoMateria` VARCHAR(10) NULL,
  `MateriaFK_DictadoMateria` INT NULL,
  `ProfesorFK_DictadoMateria` INT NULL,
  `horaInicio_DictadoMateria` TIME NULL,
  `horaFinDictado_DictadoMateria` TIME NULL,
  PRIMARY KEY (`id_DictadoMateria`),
  INDEX `MateriaFK_idx` (`MateriaFK_DictadoMateria` ASC) VISIBLE,
  INDEX `ProfesorFK_idx` (`ProfesorFK_DictadoMateria` ASC) VISIBLE,
  INDEX `ComisionFK_idx` (`ComisionFK_DictadoMateria` ASC) VISIBLE,
  CONSTRAINT `MateriaFK_DictadoMateria`
    FOREIGN KEY (`MateriaFK_DictadoMateria`)
    REFERENCES `BD_Universidad`.`Materias` (`id_Materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ProfesorFK_DictadoMateria`
    FOREIGN KEY (`ProfesorFK_DictadoMateria`)
    REFERENCES `BD_Universidad`.`Profesores` (`id_Profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ComisionFK_DictadoMateria`
    FOREIGN KEY (`ComisionFK_DictadoMateria`)
    REFERENCES `BD_Universidad`.`Comision` (`id_Comision`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_Universidad`.`DictadoAlumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_Universidad`.`DictadoAlumnos` (
  `id_DictadoAlumnos` INT NOT NULL AUTO_INCREMENT,
  `AlumnoFK_DictadoAlumnos` INT NULL,
  `DictadoFK_DictadoAlumnos` INT NULL,
  `Estado_DictadoAlumnos` ENUM("Inscripto", "Regular", "Libre", "Aprobacion Directa") NULL,
  PRIMARY KEY (`id_DictadoAlumnos`),
  INDEX `AlumnoFK_idx` (`AlumnoFK_DictadoAlumnos` ASC) VISIBLE,
  INDEX `DictadoFK_idx` (`DictadoFK_DictadoAlumnos` ASC) VISIBLE,
  CONSTRAINT `AlumnoFK_DictadoAlumnos`
    FOREIGN KEY (`AlumnoFK_DictadoAlumnos`)
    REFERENCES `BD_Universidad`.`Alumnos` (`dni_Alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `DictadoFK_DictadoAlumnos`
    FOREIGN KEY (`DictadoFK_DictadoAlumnos`)
    REFERENCES `BD_Universidad`.`DictadoMateria` (`id_DictadoMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_Universidad`.`Universidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_Universidad`.`Universidad` (
  `id_Universidad` INT NOT NULL AUTO_INCREMENT,
  `nombre_Universidad` VARCHAR(45) NULL,
  `direccion_Universidad` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Universidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_Universidad`.`Carreras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_Universidad`.`Carreras` (
  `id_Carreras` INT NOT NULL AUTO_INCREMENT,
  `UniversidadFK_Carreras` INT NULL,
  `nombre_Carreras` VARCHAR(45) NULL,
  `descripcion_Carreras` VARCHAR(45) NULL,
  `tipo_Carreras` ENUM("Ingenieria", "Licenciatura", "Postgrado", "Maestria", "Especializacion", "Tecnicatura Superior", "Curso Postgrado") NULL,
  PRIMARY KEY (`id_Carreras`),
  INDEX `UniversidadFK_idx` (`UniversidadFK_Carreras` ASC) VISIBLE,
  CONSTRAINT `UniversidadFK_Carreras`
    FOREIGN KEY (`UniversidadFK_Carreras`)
    REFERENCES `BD_Universidad`.`Universidad` (`id_Universidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_Universidad`.`PlanDeEstudios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_Universidad`.`PlanDeEstudios` (
  `id_PlanDeEstudios` INT NOT NULL AUTO_INCREMENT,
  `CarreraFK_PlanDeEstudios` INT NULL,
  `año_PlanDeEstudios` VARCHAR(45) NULL,
  `descripcion_PlanDeEstudios` VARCHAR(45) NULL,
  PRIMARY KEY (`id_PlanDeEstudios`),
  INDEX `CarreraFK_idx` (`CarreraFK_PlanDeEstudios` ASC) VISIBLE,
  CONSTRAINT `CarreraFK_PlanDeEstudios`
    FOREIGN KEY (`CarreraFK_PlanDeEstudios`)
    REFERENCES `BD_Universidad`.`Carreras` (`id_Carreras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_Universidad`.`PlanMaterias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_Universidad`.`PlanMaterias` (
  `id_PlanMaterias` INT NOT NULL AUTO_INCREMENT,
  `MateriaFK_PlanMaterias` INT NULL,
  `PlanFK_PlanMaterias` INT NULL,
  PRIMARY KEY (`id_PlanMaterias`),
  INDEX `MateriaFK_idx` (`MateriaFK_PlanMaterias` ASC) VISIBLE,
  INDEX `PlanFK_idx` (`PlanFK_PlanMaterias` ASC) VISIBLE,
  CONSTRAINT `MateriaFK_PlanMaterias`
    FOREIGN KEY (`MateriaFK_PlanMaterias`)
    REFERENCES `BD_Universidad`.`Materias` (`id_Materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PlanFK_PlanMaterias`
    FOREIGN KEY (`PlanFK_PlanMaterias`)
    REFERENCES `BD_Universidad`.`PlanDeEstudios` (`id_PlanDeEstudios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD_Universidad`.`AlumnosUniversidadCarrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BD_Universidad`.`AlumnosUniversidadCarrera` (
  `id_AlumnosUniversidadCarrera` INT NOT NULL AUTO_INCREMENT,
  `AlumnoFK_AlumnosUniversidadCarrera` INT NULL,
  `UniversidadFK_AlumnosUniversidadCarrera` INT NULL,
  `CarreraFK_AlumnosUniversidadCarrera` INT NULL,
  `legajoAlumno_AlumnosUniversidadCarrera` INT NULL,
  PRIMARY KEY (`id_AlumnosUniversidadCarrera`),
  INDEX `AlumnoFK_idx` (`AlumnoFK_AlumnosUniversidadCarrera` ASC) VISIBLE,
  INDEX `UniversidadFK_idx` (`UniversidadFK_AlumnosUniversidadCarrera` ASC) VISIBLE,
  INDEX `CarreraFK_idx` (`CarreraFK_AlumnosUniversidadCarrera` ASC) VISIBLE,
  UNIQUE INDEX `legajoAlumno_UNIQUE` (`legajoAlumno_AlumnosUniversidadCarrera` ASC) VISIBLE,
  CONSTRAINT `AlumnoFK_AlumnosUniversidadCarrera`
    FOREIGN KEY (`AlumnoFK_AlumnosUniversidadCarrera`)
    REFERENCES `BD_Universidad`.`Alumnos` (`dni_Alumno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `UniversidadFK_AlumnosUniversidadCarrera`
    FOREIGN KEY (`UniversidadFK_AlumnosUniversidadCarrera`)
    REFERENCES `BD_Universidad`.`Universidad` (`id_Universidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `CarreraFK_AlumnosUniversidadCarrera`
    FOREIGN KEY (`CarreraFK_AlumnosUniversidadCarrera`)
    REFERENCES `BD_Universidad`.`Carreras` (`id_Carreras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
